### ISSUE TITLE
Refactor: Identify working wss parachain links dynamically for chopsticks tests

### ISSUE THREAD

**Issue by bvotteler** [interlay/bridge#101]
Currently the automated chopsticks tests use configuration files with a single, hard-coded wss link as rpc endpoint. 
If, for some reason, there are issues with the rpc endpoint, chopsticks will run into errors, or may just not start correctly. This then leads to test errors which more often than not are false negatives.

Instead of using a fixed wss link, we want to use a collection of wss links, with backups mirroring the ones we use [in the UI](https://github.com/interlay/interbtc-ui/blob/1b486854eb0af10d179805a0e3b2516efd73c029/src/utils/hooks/api/xcm/xcm-endpoints.ts#L5-L25) .
We can attempt a connection race in a test perparation/setup script, similiar to [how the XCM lib does it](https://github.com/interlay/bridge/blob/e640944dccd6990944ffd549497a2b2520ad2e4e/src/api-provider.ts#L65-L67) for the api providers, and then use the endpoints that responded to construct the configuration yaml file using the wss link of the connection that won.

**Comment by bvotteler** [comment]
Marked as blocked.

The main reason for adding this was to avoid errors with Astar. And while it is feasible to run these checks, starting tests against Astar's alternative rpc wss links throw an "`RpcError: Response is too big`" error when starting chopsticks (see error message below). Meaning even if we detect that their main rpc is down, we cannot use the alternative.

This makes checking for live wss links somewhat useless until we can rely on other rpcs (and figure out a way to check that response size won't be an issue)

```bash
yarn start xcm --relaychain=configs/polkadot.yml --parachain=configs/astar.yml
chopsticks xcm

XCM setup with relaychain and parachains

Options:
      --version     Show version number                                [boolean]
  -h, --help        Show help                                          [boolean]
      --relaychain  Relaychain config file path                         [string]
      --parachain   Parachain config file path                [array] [required]

RpcError: -32702: Response is too big: Exceeded max limit of 1048576
    at checkError (/home/brendon/Documents/1_Work/DevStuff/interlay/chopsticks/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:24:15)
    at RpcCoder.decodeResponse (/home/brendon/Documents/1_Work/DevStuff/interlay/chopsticks/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:42:9)
    at WsProvider.<anonymous> (/home/brendon/Documents/1_Work/DevStuff/interlay/chopsticks/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:145:93)

```
